baseurl = "https://noping.cc/"
languageCode = "en-us"
title = "noping"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-42250843-3"

[params]
	# General information
	author = "Digitalcraftsman"
	description = "C library for ICMP pings"
	copyright = "Florian Forster"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/octo/liboping"

	version = "1.9.0"
	logo = "images/logo.png"
	favicon = "images/favicon.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[[menu.main]]
	name   = "Main"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Documentation"
	url    = "/documentation/"
	weight = 20
	identifier = "docs"

#[[menu.main]]
#	name = "liboping(3)"
#	url = "/documentation/liboping/"
#	parent = "docs"
#
#[[menu.main]]
#	name = "oping(8)"
#	url = "/documentation/oping/"
#	parent = "docs"
#
#
#[[menu.main]]
#	name = "ping_construct(3)"
#	url = "/documentation/ping_construct/"
#	parent = "docs"
#
#[[menu.main]]
#	name = "ping_get_error(3)"
#	url = "/documentation/ping_get_error/"
#	parent = "docs"
#
#[[menu.main]]
#	name = "ping_host_add(3)"
#	url = "/documentation/ping_host_add/"
#	parent = "docs"
#
#[[menu.main]]
#	name = "ping_iterator_get_context(3)"
#	url = "/documentation/ping_iterator_get_context/"
#	parent = "docs"
#
#[[menu.main]]
#	name = "ping_iterator_get_info(3)"
#	url = "/documentation/ping_iterator_get_info/"
#	parent = "docs"
#
#[[menu.main]]
#	name = "ping_get(3)"
#	url = "/documentation/ping_iterator_get/"
#	parent = "docs"
#
#[[menu.main]]
#	name = "ping_send(3)"
#	url = "/documentation/ping_send/"
#	parent = "docs"
#
#[[menu.main]]
#	name = "ping_setopt(3)"
#	url = "/documentation/ping_setopt/"
#	parent = "docs"

[social]
	twitter = "flocto"
	github  = "octo"
	email   = "liboping@verplant.org"


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
